require('common');

local settings = T{ };
settings["commandPresets"] = T{ };
settings["commandPresets"][1] = T{ };
settings["commandPresets"][2] = T{ };
settings["commandPresets"][3] = T{ };
settings["commandPresets"][4] = T{ };
settings["commandPresets"][5] = T{ };
settings["commandPresets"][6] = T{ };
settings["commandPresets"][1]["quantity"] = 80;
settings["commandPresets"][1]["command"] = "/ma \"Pollen\" <me>";
settings["commandPresets"][1]["name"] = "BluMagic";
settings["commandPresets"][1]["interval"] = 7.5;
settings["commandPresets"][2]["quantity"] = 100;
settings["commandPresets"][2]["command"] = "/up \"Knight's Minne\" <me>;/wait 10;/up \"Valor Minuet\" <me>;/wait 10;/up \"Army's Paeon\" <me>;/wait 10;/up \"Sword Madrigal\" <me>;/wait 10;/up \"Sheepfoe Mambo\" <me>;/wait 10;/up \"Mage's Ballad\" <me>;/wait 10;/up \"Advancing March\" <me>";
settings["commandPresets"][2]["name"] = "Song";
settings["commandPresets"][2]["interval"] = 10;
settings["commandPresets"][3]["quantity"] = 100;
settings["commandPresets"][3]["command"] = "/ma \"Carbuncle\" <me>;/wait 9;/pet Release <me>;/wait 1;/ma \"Fenrir\" <me>;/wait 9;/pet Release <me>";
settings["commandPresets"][3]["name"] = "Summoning";
settings["commandPresets"][3]["interval"] = 1;
settings["commandPresets"][4]["quantity"] = 1;
settings["commandPresets"][4]["command"] = "/lastsynth";
settings["commandPresets"][4]["name"] = "Crafting";
settings["commandPresets"][4]["interval"] = 23;
settings["commandPresets"][5]["quantity"] = 500;
settings["commandPresets"][5]["command"] = "/dig";
settings["commandPresets"][5]["name"] = "Dig";
settings["commandPresets"][5]["interval"] = 3.5;
settings["commandPresets"][6]["quantity"] = 100;
settings["commandPresets"][6]["command"] = "/fish";
settings["commandPresets"][6]["name"] = "Fishing";
settings["commandPresets"][6]["interval"] = 25;

return settings;
