require('common');

local settings = T{ };
settings["commandPresets"] = T{ };
settings["commandPresets"][1] = T{ };
settings["commandPresets"][2] = T{ };
settings["commandPresets"][3] = T{ };
settings["commandPresets"][4] = T{ };
settings["commandPresets"][5] = T{ };
settings["commandPresets"][1]["quantity"] = 100;
settings["commandPresets"][1]["command"] = "/up \"Knight's Minne\" <me>;/wait 10;/up \"Valor Minuet\" <me>;/wait 10;/up \"Army's Paeon\" <me>;/wait 10;/up \"Sword Madrigal\" <me>;/wait 10;/up \"Sheepfoe Mambo\" <me>;/wait 10;/up \"Mage's Ballad\" <me>;/wait 10;/up \"Advancing March\" <me>";
settings["commandPresets"][1]["name"] = "Song";
settings["commandPresets"][1]["interval"] = 10;
settings["commandPresets"][2]["quantity"] = 1;
settings["commandPresets"][2]["command"] = "/lastsynth";
settings["commandPresets"][2]["name"] = "Crafting";
settings["commandPresets"][2]["interval"] = 23;
settings["commandPresets"][3]["quantity"] = 500;
settings["commandPresets"][3]["command"] = "/dig";
settings["commandPresets"][3]["name"] = "Dig";
settings["commandPresets"][3]["interval"] = 3.5;
settings["commandPresets"][4]["quantity"] = 100;
settings["commandPresets"][4]["command"] = "/fish";
settings["commandPresets"][4]["name"] = "Fishing";
settings["commandPresets"][4]["interval"] = 25;
settings["commandPresets"][5]["quantity"] = 100;
settings["commandPresets"][5]["command"] = "/ma Bio <t>";
settings["commandPresets"][5]["name"] = "Dark Magic";
settings["commandPresets"][5]["interval"] = 3.5;

return settings;
